@section('title') 
PPSDM Aparatur - Tambah Peserta
@endsection
@extends('layouts.main')
@section('style')
<!-- Select2 CSS -->
<link href="{{ asset('assets/plugins/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />
<!-- Tagsinput CSS -->
<link href="{{ asset('assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput-typeahead.css') }}" rel="stylesheet" type="text/css" />
@endsection 
@section('content')
<!-- Start XP Breadcrumbbar -->                    
<div class="xp-breadcrumbbar">
    <div class="row">
        <div class="col-md-6 col-lg-6">
        </div>
        <div class="col-md-6 col-lg-6">
            <div class="xp-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}"><i class="icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="{{ route('mata_anggaran.index') }}">SPD</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Tambah Peserta</li>
                </ol>
            </div>
        </div>
    </div>          
</div>
<!-- End XP Breadcrumbbar -->
<!-- Start XP Contentbar -->    
<div class="xp-contentbar">
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-header bg-white">
                <h5 class="card-title text-black">Tambah Peserta</h5>
                <h6 class="card-subtitle"> - Unit Bagian Umum -</h6>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('spd.peserta.store') }}" onsubmit="return Validation()" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                      <label for="akun">Nama Peserta</label>
                      <input type="number" required name="akun" min="0" class="form-control" id="akun" placeholder="Nama Peserta">
                    </div>
                    <div class="form-group">
                      <label for="akun">No Peserta</label>
                      <input type="number" required name="akun" min="0" class="form-control" id="akun" placeholder="Nomor Peserta">
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group col-md-6">
                        <label for="inputAddress">Kota Asal *</label>
                        <select class="xp-select2-single form-control" name="kota_asal">
                            <option>Pilih Kota Asal</option>
                            <option value="4" >Banda Aceh</option>
                            <option value="7" >Banjarmasin</option>
                            <option value="8" >Batam</option>
                            <option value="10" >Biak</option>
                            <option value="11" >Blora</option>
                            <option value="12" >Bogor</option>
                            <option value="13" >Denpasar</option>
                            <option value="14" >Gorontalo</option>
                            <option value="15" >Jambi</option>
                            <option value="16" >Jayapura</option>
                            <option value="17" >Yogyakarta</option>
                            <option value="18" >Kendari</option>
                            <option value="19" >Kupang</option>
                            <option value="20" >Makassar</option>
                            <option value="21" >Malang</option>
                            <option value="22" >Mamuju</option>
                            <option value="23" >Manado</option>
                            <option value="24" >Manokwari</option>
                            <option value="25" >Mataram</option>
                            <option value="26" >Medan</option>
                            <option value="27" >Padang</option>
                            <option value="28" >Palangkaraya</option>
                            <option value="29" >Palembang</option>
                            <option value="30" >Palu</option>
                            <option value="32" >Pekanbaru</option>
                            <option value="33" >Pontianak</option>
                            <option value="34" >Poso</option>
                            <option value="35" >Semarang</option>
                            <option value="36" >Solo</option>
                            <option value="37" >Sorong</option>
                            <option value="41" >Ternate</option>
                            <option value="42" >Timika</option>
                            <option value="43" >Toli-Toli</option>
                            <option value="44" >Purwakarta</option>
                            <option value="45" >Tokyo</option>
                            <option value="47" >Cirebon</option>
                            <option value="48" >Bekasi</option>
                            <option value="49" >Paris</option>
                            <option value="51" >Pekalongan</option>
                            <option value="53" >Tanjung Pinang</option>
                            <option value="54" >Cepu</option>
                            <option value="56" >Kunming</option>
                            <option value="61" >Serang</option>
                            <option value="62" >London</option>
                            <option value="63" >Jerman</option>
                            <option value="64" >Abu Dhabi</option>
                            <option value="65" >Hongkong</option>
                            <option value="68" >Waikabubak</option>
                            <option value="69" >Tambolaka</option>
                            <option value="70" >Sukawinatan</option>
                            <option value="74" >Cilacap</option>
                            <option value="75" >Dumai</option>
                            <option value="77" >Ketapang</option>
                            <option value="78" >Tarakan</option>
                            <option value="79" >Pacitan</option>
                            <option value="80" >Rembang</option>
                            <option value="81" >Pedan</option>
                            <option value="82" >Klaten</option>
                            <option value="83" >Adipala</option>
                            <option value="85" >Kediri</option>
                            <option value="87" >Kutai</option>
                            <option value="89" >Tegal</option>
                            <option value="90" >Brebes</option>
                            <option value="91" >Purwokerto</option>
                            <option value="92" >Bangli</option>
                            <option value="93" >Buleleng</option>
                            <option value="94" >Gianyar</option>
                            <option value="95" >Karangasem</option>
                            <option value="96" >Badung</option>
                            <option value="97" >Tabanan</option>
                            <option value="98" >Klungkung</option>
                            <option value="99" >Jembrana</option>
                            <option value="102" >Pemalang</option>
                            <option value="103" >Purbalingga</option>
                            <option value="104" >Batang</option>
                            <option value="105" >Banyumas</option>
                            <option value="106" >Banjarnegara</option>
                            <option value="107" >Kebumen</option>
                            <option value="108" >Wonogiri</option>
                            <option value="109" >Sragen</option>
                            <option value="110" >Sukoharjo</option>
                            <option value="111" >Boyolali</option>
                            <option value="112" >Demak</option>
                            <option value="113" >Purworejo</option>
                            <option value="114" >Magelang</option>
                            <option value="121" >Palopo</option>
                            <option value="122" >Singapura</option>
                            <option value="125" >Samarinda</option>
                            <option value="126" >Pomalaa</option>
                            <option value="127" >Beijing</option>
                            <option value="128" >Meulaboh</option>
                            <option value="129" >New Delhi</option>
                            <option value="130" >Karnataka</option>
                            <option value="131" >Singkep</option>
                            <option value="132" >Lingga</option>
                            <option value="133" >Saumlaki</option>
                            <option value="134" >Sabang</option>
                            <option value="136" >Kendawangan</option>
                            <option value="137" >Jailolo</option>
                            <option value="138" >Halmahera Barat</option>
                            <option value="140" >Tanah Laut</option>
                            <option value="143" >Topang</option>
                            <option value="144" >Meranti</option>
                            <option value="145" >Selat Sugi</option>
                            <option value="146" >Aru Selatan</option>
                            <option value="147" >Wokam Aru Utara</option>
                            <option value="148" >Kaimana</option>
                            <option value="149" >Fak-fak</option>
                            <option value="150" >Toya Pakeh</option>
                            <option value="151" >Nusa Penida</option>
                            <option value="152" >Delta Mahakam</option>
                            <option value="153" >Simeulue</option>
                            <option value="154" >Aceh Singkil</option>
                            <option value="155" >Aceh Selatan</option>
                            <option value="156" >Aceh Tenggara</option>
                            <option value="157" >Aceh Timur</option>
                            <option value="158" >Aceh Tengah</option>
                            <option value="159" >Aceh Barat</option>
                            <option value="160" >Aceh Besar</option>
                            <option value="161" >Pidie</option>
                            <option value="162" >Bireuen</option>
                            <option value="163" >Aceh Utara</option>
                            <option value="164" >Aceh Barat Daya</option>
                            <option value="165" >Gayo Lues</option>
                            <option value="166" >Aceh Tamiang</option>
                            <option value="167" >Nagan Raya</option>
                            <option value="168" >Aceh Jaya</option>
                            <option value="169" >Bener Meriah</option>
                            <option value="170" >Pidie Jaya</option>
                            <option value="171" >Langsa</option>
                            <option value="172" >Lhokseumawe</option>
                            <option value="173" >Subulussalam</option>
                            <option value="174" >Nias</option>
                            <option value="175" >Mandailing Natal</option>
                            <option value="176" >Tapanuli Selatan</option>
                            <option value="177" >Tapanuli Tengah</option>
                            <option value="178" >Tapanuli Utara</option>
                            <option value="180" >Labuhan Batu</option>
                            <option value="181" >Asahan</option>
                            <option value="50" >Jakarta</option>
                            <option value="39" >Tangerang Selatan</option>
                            <option value="60" >Tangerang</option>
                            <option value="141" >Tasikmalaya</option>
                            <option value="46" >Sukabumi</option>
                            <option value="76" >Garut</option>
                            <option value="116" >Ciamis</option>
                            <option value="72" >Cianjur</option>
                            <option value="88" >Banten</option>
                            <option value="100" >Pandeglang</option>
                            <option value="5" >Bandar Lampung</option>
                            <option value="9" >Bengkulu</option>
                            <option value="120" >Sumedang</option>
                            <option value="119" >Karawang</option>
                            <option value="31" >Pangkal Pinang</option>
                            <option value="118" >Kuningan</option>
                            <option value="115" >Majalengka</option>
                            <option value="124" >Cisarua</option>
                            <option value="66" >Indramayu</option>
                            <option value="182" >Simalungun</option>
                            <option value="183" >Dairi</option>
                            <option value="184" >Karo</option>
                            <option value="185" >Deli Serdang</option>
                            <option value="186" >Langkat</option>
                            <option value="187" >Nias Selatan</option>
                            <option value="188" >Humbang Hasundutan</option>
                            <option value="189" >Pakpak barat</option>
                            <option value="190" >Samosir</option>
                            <option value="191" >Serdang Bedagai</option>
                            <option value="192" >Batu Bara</option>
                            <option value="52" >Cibinong</option>
                            <option value="101" >Lebak</option>
                            <option value="193" >Padang Lawas Utara</option>
                            <option value="194" >Padang Lawas</option>
                            <option value="195" >Labuhan Batu Selatan</option>
                            <option value="196" >Labuhan Batu Utara</option>
                            <option value="197" >Nias Utara</option>
                            <option value="198" >Nias Barat</option>
                            <option value="199" >Sibolga</option>
                            <option value="200" >Tanjung Barat</option>
                            <option value="201" >Pematang Siantar</option>
                            <option value="202" >Tebing Tinggi</option>
                            <option value="203" >Binjai</option>
                            <option value="204" >Padangsidimpuan</option>
                            <option value="205" >Gunungsitoli</option>
                            <option value="206" >Kepulauan Mentawai</option>
                            <option value="207" >Pesisir selatan</option>
                            <option value="208" >Sijunjung</option>
                            <option value="209" >Tanah Datar</option>
                            <option value="210" >Padang Pariaman</option>
                            <option value="211" >Agam</option>
                            <option value="212" >Lima Puluh Kota</option>
                            <option value="213" >Pasaman</option>
                            <option value="214" >Solok Selatan</option>
                            <option value="215" >Dharmasraya</option>
                            <option value="216" >Pasaman Barat</option>
                            <option value="217" >Solok</option>
                            <option value="218" >Sawah Lunto</option>
                            <option value="219" >Padang Panjang</option>
                            <option value="220" >Bukittinggi</option>
                            <option value="221" >Payakumbuh</option>
                            <option value="222" >Pariaman</option>
                            <option value="223" >Kuantan singingi</option>
                            <option value="224" >Indragiri Hulu</option>
                            <option value="225" >Indragiri Hilir</option>
                            <option value="226" >Pelalawan</option>
                            <option value="227" >Siak</option>
                            <option value="228" >Kampar</option>
                            <option value="229" >Bengkalis</option>
                            <option value="230" >Rokan Hilir</option>
                            <option value="231" >Kepulauan Meranti</option>
                            <option value="232" >Kerinci</option>
                            <option value="233" >Merangin</option>
                            <option value="234" >Sarolangun</option>
                            <option value="235" >Batang Hari</option>
                            <option value="236" >Muaro Jambi</option>
                            <option value="237" >Tanjung Jabung TImur</option>
                            <option value="238" >Tanjung Jabung Barat</option>
                            <option value="239" >Tebo</option>
                            <option value="240" >Bungo</option>
                            <option value="241" >Sungai Penuh</option>
                            <option value="242" >Ogan Komering Ulu</option>
                            <option value="243" >Ogan Komering Ilir</option>
                            <option value="244" >Muara Enim</option>
                            <option value="245" >Bolaang Mongondow Utara</option>
                            <option value="246" >Siau Tagulandang Biaro</option>
                            <option value="247" >Minahasa Tenggara</option>
                            <option value="248" >Bolaang Mongondow Selatan</option>
                            <option value="249" >Bolaang Mongondow Timur</option>
                            <option value="250" >Bitung</option>
                            <option value="251" >Tomohon</option>
                            <option value="252" >Kotamobagu</option>
                            <option value="253" >Banggai Kepulauan</option>
                            <option value="254" >Banggai</option>
                            <option value="255" >Morowali</option>
                            <option value="256" >Donggala</option>
                            <option value="257" >Buol</option>
                            <option value="258" >Parigi Moutong</option>
                            <option value="259" >Tojo Una-Una</option>
                            <option value="260" >Sigi</option>
                            <option value="261" >Selayar</option>
                            <option value="262" >Bulukumba</option>
                            <option value="263" >Bantaeng</option>
                            <option value="264" >Jeneponto</option>
                            <option value="265" >Takalar</option>
                            <option value="266" >Gowa</option>
                            <option value="267" >Sinjai</option>
                            <option value="268" >Maros</option>
                            <option value="269" >Pangkajene Dan Kepulauan</option>
                            <option value="270" >Barru</option>
                            <option value="271" >Bone</option>
                            <option value="272" >Soppeng</option>
                            <option value="273" >Wajo</option>
                            <option value="274" >Sidenreng Rappang</option>
                            <option value="275" >Pinrang</option>
                            <option value="276" >Enrekang</option>
                            <option value="277" >Luwu</option>
                            <option value="278" >Tana Toraja</option>
                            <option value="279" >Luwu Utara</option>
                            <option value="280" >Luwu Timur</option>
                            <option value="281" >Toraja Utara</option>
                            <option value="282" >Pare-Pare</option>
                            <option value="283" >Buton</option>
                            <option value="284" >Muna</option>
                            <option value="285" >Konawe</option>
                            <option value="286" >Kolaka</option>
                            <option value="287" >Konawe Selatan</option>
                            <option value="288" >Bombana</option>
                            <option value="289" >Lahat</option>
                            <option value="290" >Musi Rawas</option>
                            <option value="291" >Musi Banyuasin</option>
                            <option value="292" >Banyuasin</option>
                            <option value="293" >Empat Lawang</option>
                            <option value="294" >Prabumulih</option>
                            <option value="295" >Pagar Alam</option>
                            <option value="296" >Lubuklinggau</option>
                            <option value="324" >Karimun</option>
                            <option value="325" >Bintan</option>
                            <option value="326" >Natuna</option>
                            <option value="327" >Kepulauan Anambas</option>
                            <option value="328" >Kepulauan Seribu</option>
                            <option value="329" >Jakarta Selatan</option>
                            <option value="330" >Jakarta Timur</option>
                            <option value="331" >Jakarta Pusat</option>
                            <option value="332" >Jakarta Barat</option>
                            <option value="333" >Jakarta Utara</option>
                            <option value="337" >Wonosobo</option>
                            <option value="338" >Karanganyar</option>
                            <option value="339" >Grobogan</option>
                            <option value="340" >Pati</option>
                            <option value="341" >Kudus</option>
                            <option value="342" >Jepara</option>
                            <option value="343" >Temanggung</option>
                            <option value="344" >Kendal</option>
                            <option value="345" >Salatiga</option>
                            <option value="346" >Kulon Progo</option>
                            <option value="347" >Bantul</option>
                            <option value="348" >Gunung Kidul</option>
                            <option value="349" >Sleman</option>
                            <option value="350" >Ponorogo</option>
                            <option value="351" >Trenggalek</option>
                            <option value="352" >Tulungagung</option>
                            <option value="334" >Bandung Barat</option>
                            <option value="319" >Bangka</option>
                            <option value="335" >Cimahi</option>
                            <option value="323" >Belitung Timur</option>
                            <option value="353" >Blitar</option>
                            <option value="354" >Lumajang</option>
                            <option value="355" >Jember</option>
                            <option value="356" >Banyuwangi</option>
                            <option value="357" >Bondowoso</option>
                            <option value="358" >Situbondo</option>
                            <option value="359" >Probolinggo</option>
                            <option value="360" >Pasuruan</option>
                            <option value="361" >Sidoarjo</option>
                            <option value="362" >Mojokerto</option>
                            <option value="363" >Jombang</option>
                            <option value="364" >Nganjuk</option>
                            <option value="365" >Madiun</option>
                            <option value="303" >Bengkulu Tengah</option>
                            <option value="304" >Bengkulu Utara</option>
                            <option value="298" >Kaur</option>
                            <option value="302" >Kepahiang</option>
                            <option value="301" >Lebong</option>
                            <option value="300" >Mukomuko</option>
                            <option value="322" >Bangka Selatan</option>
                            <option value="315" >Kabupaten Pringsewu</option>
                            <option value="299" >Seluma</option>
                            <option value="313" >Kabupaten Tulang Bawang</option>
                            <option value="316" >Kabupaten Mesuji</option>
                            <option value="318" >Metro</option>
                            <option value="320" >Bangka Barat</option>
                            <option value="311" >Kabupaten Lampung Utara</option>
                            <option value="307" >Kabupaten Tanggamus</option>
                            <option value="321" >Bangka Tengah</option>
                            <option value="308" >Kabupaten Lampung Selatan</option>
                            <option value="310" >Kabupaten Lampung Tengah</option>
                            <option value="309" >Kabupaten Lampung Timur</option>
                            <option value="312" >Kabupaten Way Kanan</option>
                            <option value="366" >Magetan</option>
                            <option value="367" >Ngawi</option>
                            <option value="368" >Bojonegoro</option>
                            <option value="369" >Tuban</option>
                            <option value="370" >Lamongan</option>
                            <option value="371" >Gresik</option>
                            <option value="372" >Bangkalan</option>
                            <option value="373" >Sampang</option>
                            <option value="374" >Pamekasan</option>
                            <option value="375" >Sumenep</option>
                            <option value="376" >Batu</option>
                            <option value="377" >Karang Asem</option>
                            <option value="378" >Lombok Barat</option>
                            <option value="379" >Lombok Tengah</option>
                            <option value="380" >Lombok Timur</option>
                            <option value="381" >Sumbawa</option>
                            <option value="382" >Dompu</option>
                            <option value="383" >Bima</option>
                            <option value="384" >Sumbawa Barat</option>
                            <option value="385" >Lombok Utara</option>
                            <option value="386" >Sumba Barat</option>
                            <option value="387" >Sumba Timur</option>
                            <option value="388" >Timor Tengah Selatan</option>
                            <option value="389" >Timor Tengah Utara</option>
                            <option value="390" >Belu</option>
                            <option value="391" >Alor</option>
                            <option value="392" >Lembata</option>
                            <option value="393" >Flores Timur</option>
                            <option value="394" >Sikka</option>
                            <option value="395" >Ende</option>
                            <option value="396" >Ngada</option>
                            <option value="397" >Manggarai</option>
                            <option value="398" >Rote Ndao</option>
                            <option value="399" >Manggarai Barat</option>
                            <option value="400" >Sumba Tengah</option>
                            <option value="401" >Sumba Barat Daya</option>
                            <option value="402" >Nagekeo</option>
                            <option value="403" >Manggarai Timur</option>
                            <option value="404" >Sabu Raijua</option>
                            <option value="405" >Sambas</option>
                            <option value="406" >Bengkayang</option>
                            <option value="407" >Landak</option>
                            <option value="408" >Sanggau</option>
                            <option value="409" >Sintang</option>
                            <option value="410" >Kapuas Hulu</option>
                            <option value="411" >Sekadau</option>
                            <option value="412" >Melawi</option>
                            <option value="413" >Kayong Utara</option>
                            <option value="414" >Wakatobi</option>
                            <option value="415" >Kolaka Utara</option>
                            <option value="416" >Buton Utara</option>
                            <option value="417" >Konawe Utara</option>
                            <option value="418" >Bau-Bau</option>
                            <option value="419" >Boalemo</option>
                            <option value="420" >Pohuwato</option>
                            <option value="421" >Bone Bolango</option>
                            <option value="422" >Gorontalo Utara</option>
                            <option value="423" >Majene</option>
                            <option value="424" >Polewali Mandar</option>
                            <option value="425" >Mamasa</option>
                            <option value="426" >Mamuju Utara</option>
                            <option value="427" >Maluku Tenggara Barat</option>
                            <option value="428" >Maluku Tenggara</option>
                            <option value="429" >Maluku Tengah</option>
                            <option value="430" >Buru</option>
                            <option value="431" >Kepulauan Aru</option>
                            <option value="432" >Seram Bagian Barat</option>
                            <option value="433" >Seram Bagian Timur</option>
                            <option value="434" >Maluku Barat Daya</option>
                            <option value="435" >Buru Selatan</option>
                            <option value="436" >Tual</option>
                            <option value="437" >Halmahera Tengah</option>
                            <option value="438" >Kepulauan Sula</option>
                            <option value="439" >Halmahera Selatan</option>
                            <option value="440" >Halmahera Utara</option>
                            <option value="441" >Halmahera Timur</option>
                            <option value="442" >Pulau Morotai</option>
                            <option value="443" >Tidore Kepulauan</option>
                            <option value="444" >Fakfak</option>
                            <option value="445" >Teluk Wondama</option>
                            <option value="446" >Teluk Bintuni</option>
                            <option value="447" >Sorong Selatan</option>
                            <option value="448" >Raja Ampat</option>
                            <option value="449" >Tambrauw</option>
                            <option value="450" >Maybrat</option>
                            <option value="451" >Merauke</option>
                            <option value="452" >Jayawijaya</option>
                            <option value="453" >Nabire</option>
                            <option value="454" >Kepulauan Yapen</option>
                            <option value="455" >Biak Numfor</option>
                            <option value="456" >Paniai</option>
                            <option value="457" >Puncak Jaya</option>
                            <option value="458" >Mimika</option>
                            <option value="459" >Boven Digoel</option>
                            <option value="460" >Mappi</option>
                            <option value="461" >Asmat</option>
                            <option value="462" >Yahukimo</option>
                            <option value="463" >Pegunungan Bintang</option>
                            <option value="464" >Tolikara</option>
                            <option value="465" >Sarmi</option>
                            <option value="467" >Waropen</option>
                            <option value="468" >Kubu Raya</option>
                            <option value="469" >Singkawang</option>
                            <option value="470" >Kotawaringin Barat</option>
                            <option value="471" >Kotawaringin Timur</option>
                            <option value="472" >Kapuas</option>
                            <option value="473" >Barito Selatan</option>
                            <option value="474" >Barito Utara</option>
                            <option value="475" >Sukamara</option>
                            <option value="476" >Lamandau</option>
                            <option value="477" >Seruyan</option>
                            <option value="478" >Katingan</option>
                            <option value="479" >Pulau Pisau</option>
                            <option value="480" >Gunung mas</option>
                            <option value="481" >Barito Timur</option>
                            <option value="482" >Murung Raya</option>
                            <option value="483" >Kota Baru</option>
                            <option value="484" >Banjar Kalimantan Selatan</option>
                            <option value="485" >Barito Kuala</option>
                            <option value="486" >Tapin</option>
                            <option value="487" >Hulu Sungai Selatan</option>
                            <option value="488" >Hulu Sungai Tengah</option>
                            <option value="489" >Hulu sungai Utara</option>
                            <option value="490" >Tabalong</option>
                            <option value="491" >Tanah Bumbu</option>
                            <option value="492" >Balangan</option>
                            <option value="493" >Banjar Baru</option>
                            <option value="494" >Paser</option>
                            <option value="495" >Kutai Barat</option>
                            <option value="496" >Kutai Kartanegara</option>
                            <option value="497" >Kutai timur</option>
                            <option value="498" >Berau</option>
                            <option value="499" >Malinau</option>
                            <option value="500" >Bulungan</option>
                            <option value="501" >Nunukan</option>
                            <option value="502" >Penajam Paser Utara</option>
                            <option value="503" >Tana Tidung</option>
                            <option value="504" >Bontang</option>
                            <option value="505" >Kepulauan Sangihe</option>
                            <option value="506" >Kepulauan Talaud</option>
                            <option value="507" >Minahasa</option>
                            <option value="508" >Minahasa Selatan</option>
                            <option value="509" >Minahasa Utara</option>
                            <option value="510" >Sampit</option>
                            <option value="511" >New York</option>
                            <option value="512" >Luwuk</option>
                            <option value="516" >Papua Nugini</option>
                            <option value="517" >Wina</option>
                            <option value="518" >Paiton</option>
                            <option value="519" >Teheran</option>
                            <option value="57" >Luang Prabang</option>
                            <option value="520" >Berlin</option>
                            <option value="521" >Bonn</option>
                            <option value="522" >Dubai</option>
                            <option value="523" >Azerbaijan</option>
                            <option value="525" >Bandung</option>
                            <option value="526" >Subang</option>
                            <option value="527" >Depok</option>
                            <option value="513" >Cikampek</option>
                            <option value="528" >Surabaya</option>
                            <option value="529" >Pangandaran</option>
                            <option value="336" >Banjar Jawa Barat</option>
                            <option value="530" >Cilegon</option>
                            <option value="531" >Belitung</option>
                            <option value="532" >Kabupaten Bandung</option>
                            <option value="533" >Balikpapan</option>
                            <option value="534" >Mempawah</option>
                            <option value="535" >Wayame</option>
                            <option value="536" >Baubau</option>
                            <option value="537" >Ambon</option>
                            <option value="538" >Tanjung Selor</option>
                            <option value="539" >Taliabu</option>
                            <option value="540" >Sidrap</option>
                            <option value="541" >Sofifi</option>
                            <option value="542" >Semeru</option>
                            <option value="73" >Cikarang</option>
                            <option value="305" >Bengkulu Selatan</option>
                            <option value="297" >Rejang Lebong</option>
                            <option value="543" >Kabupaten Tangerang</option>
                            <option value="544" >Jenewa</option>
                            <option value="545" >Kabupaten Bekasi</option>
                            <option value="546" >Kabupaten Bogor</option>
                            <option value="547" >Pangkep</option>
                            <option value="548" >Deiyai</option>
                            <option value="549" >Mamuju Tengah</option>
                            <option value="550" >Teheran</option>
                            <option value="551" >Doha</option>
                            <option value="552" >Cape Town</option>
                            <option value="553" >Davos</option>
                            <option value="555" >Barcelona</option>
                            <option value="556" >Kigali</option>
                            <option value="557" >Ulan Bator</option>
                            <option value="558" >Amsterdam</option>
                            <option value="559" >Copenhagen</option>
                            <option value="560" >Oslo</option>
                            <option value="561" >Reykjavik</option>
                            <option value="562" >Stockholm</option>
                            <option value="563" >Brussel</option>
                            <option value="564" >Labuan Bajo</option>
                            <option value="565" >Babo</option>
                            <option value="566" >Pasangkayu</option>
                            <option value="567" >Penukal Abab Lematang Ilir</option>
                            <option value="568" >Pegunungan Arfak</option>
                            <option value="569" >Lanny Jaya</option>
                            <option value="570" >Sydney</option>
                            <option value="571" >Nevada</option>
                            <option value="572" >Kongens Lyngby</option>
                            <option value="573" >Milan</option>
                            <option value="574" >Ottawa</option>
                            <option value="575" >Vancouver</option>
                            <option value="576" >Edmonton</option>
                            <option value="577" >Kuala Lumpur</option>
                            <option value="578" >Brisbane</option>
                            <option value="579" >Melbourne</option>
                            <option value="580" >Pittsburgh</option>
                            <option value="581" >Ho Chi Minh</option>
                            <option value="582" >Vienna</option>
                            <option value="583" >Bangkok</option>
                            <option value="584" >Sapporo</option>
                            <option value="585" >Aberdeen</option>
                            <option value="586" >Sussex</option>
                            <option value="587" >Ogan Ilir</option>
                            <option value="588" >Kabupaten Probolinggo</option>
                            <option value="589" >Kabupaten Pasuruan</option>
                            <option value="590" >Manila</option>
                            <option value="591" >Seoul</option>
                            <option value="592" >Rokan Hulu</option>
                            <option value="593" >Helsinki</option>
                            <option value="594" >Sharm el-Sheikh</option>
                            <option value="596" >Busan</option>
                            <option value="597" >Kairo</option>
                            <option value="598" >Kabupaten Semarang</option>
                            <option value="599" >Kabupaten Magelang</option>
                            <option value="600" >Kabupaten Tegal</option>
                            <option value="601" >Roma</option>
                            <option value="602" >Batulicin</option>
                            <option value="603" >Canberra</option>
                            <option value="604" >Kepulauan Tanimbar</option>
                            <option value="605" >Lawe-Lawe</option>
                            <option value="606" >Balongan</option>
                            <option value="607" >Daejeon</option>
                            <option value="608" >Perth</option>
                            <option value="179" >Toba</option>
                            <option value="609" >Riyadh</option>
                            <option value="306" >Kabupaten Lampung Barat</option>
                            <option value="314" >Kabupaten Pesawaran</option>
                            <option value="610" >Kabupaten Pesisir Barat</option>
                            <option value="317" >Kabupaten Tulang Bawang Barat</option>
                            <option value="611" >Bengaluru</option>
                            <option value="612" >Budapest</option>
                            <option value="514" >Washington</option>
                            <option value="613" >Houston</option>
                            <option value="614" >Kabupaten Cirebon</option>
                            <option value="615" >California</option>
                            <option value="616" >Kabupaten Bolaang Mongondow</option>
                            <option value="617" >Gandhinagar</option>
                            <option value="618" >Merak</option>
                            <option value="619" >Cilegon</option>
                            <option value="620" >Vientiane</option>
                            <option value="621" >Nanning</option>
                            <option value="622" >Mumbai</option>
                            <option value="623" >Detroit</option>
                            <option value="624" >Pnom Penh</option>
                            <option value="625" >Moskow</option>
                            <option value="626" >Rotterdam</option>
                            <option value="627" >Gibraltar</option>
                            <option value="628" >Dakar</option>
                            <option value="466" >Kabupaten Keerom</option>
                            <option value="629" >Kyoto</option>
                            <option value="630" >Hanoi</option>
                            <option value="631" >Da Nang</option>
                            <option value="632" >Goa</option>
                            <option value="633" >Nanjing</option>
                            <option value="634" >Fuzhou</option>
                            <option value="635" >Shanghai</option>
                            <option value="636" >Bergen</option>
                            <option value="637" >Manokwari Selatan</option>
                            <option value="638" >Bern</option>
                            <option value="639" >Miami</option>
                            <option value="640" >Chicago</option>
                            <option value="641" >Seattle</option>
                            <option value="642" >Illinois</option>
                            <option value="643" >Andowia</option>
                            <option value="644" >Lamonae</option>
                            <option value="645" >Nairobi</option>
                            <option value="646" >Dar es Salaam</option>
                            <option value="647" >Madrid</option>
                            <option value="648" >Supiori</option>
                            <option value="649" >Kabupaten Malaka</option>
                            <option value="650" >Marquette</option>
                            <option value="651" >Sudbury</option>
                            <option value="653" >Haikou</option>
                            <option value="652" >Wuxi City</option>
                            <option value="654" >Calgary</option>
                            <option value="655" >Hainan</option>
                            <option value="656" >Guangzhou</option>
                            <option value="657" >Kushiro</option>
                            <option value="658" >Palawan</option>
                            <option value="659" >Tanjung Balai</option>
                            <option value="661" >Astana</option>
                            <option value="662" >Hokkaido</option>
                            <option value="663" >Shenzhen</option>
                            <option value="664" >Auckland</option>
                            <option value="665" >Phang Nga Bay</option>
                            <option value="666" >Bandar Seri Begawan</option>
                            <option value="667" >San Fransisco</option>
                            <option value="668" >Johor Bahru</option>
                            <option value="669" >Santiago</option>
                            <option value="670" >Mandalika</option>
                            <option value="671" >Kabupaten Karawang</option>
                        </select>
                        </div>
                        <div class="form-group col-md-6">
                        <label for="inputAddress">Kota Tujuan *</label>
                        <select class="xp-select2-single form-control" name="kota_tujuan">
                            <option>Pilih Kota Tujuan</option>
                            <option value="4" >Banda Aceh</option>
                            <option value="7" >Banjarmasin</option>
                            <option value="8" >Batam</option>
                            <option value="10" >Biak</option>
                            <option value="11" >Blora</option>
                            <option value="12" >Bogor</option>
                            <option value="13" >Denpasar</option>
                            <option value="14" >Gorontalo</option>
                            <option value="15" >Jambi</option>
                            <option value="16" >Jayapura</option>
                            <option value="17" >Yogyakarta</option>
                            <option value="18" >Kendari</option>
                            <option value="19" >Kupang</option>
                            <option value="20" >Makassar</option>
                            <option value="21" >Malang</option>
                            <option value="22" >Mamuju</option>
                            <option value="23" >Manado</option>
                            <option value="24" >Manokwari</option>
                            <option value="25" >Mataram</option>
                            <option value="26" >Medan</option>
                            <option value="27" >Padang</option>
                            <option value="28" >Palangkaraya</option>
                            <option value="29" >Palembang</option>
                            <option value="30" >Palu</option>
                            <option value="32" >Pekanbaru</option>
                            <option value="33" >Pontianak</option>
                            <option value="34" >Poso</option>
                            <option value="35" >Semarang</option>
                            <option value="36" >Solo</option>
                            <option value="37" >Sorong</option>
                            <option value="41" >Ternate</option>
                            <option value="42" >Timika</option>
                            <option value="43" >Toli-Toli</option>
                            <option value="44" >Purwakarta</option>
                            <option value="45" >Tokyo</option>
                            <option value="47" >Cirebon</option>
                            <option value="48" >Bekasi</option>
                            <option value="49" >Paris</option>
                            <option value="51" >Pekalongan</option>
                            <option value="53" >Tanjung Pinang</option>
                            <option value="54" >Cepu</option>
                            <option value="56" >Kunming</option>
                            <option value="61" >Serang</option>
                            <option value="62" >London</option>
                            <option value="63" >Jerman</option>
                            <option value="64" >Abu Dhabi</option>
                            <option value="65" >Hongkong</option>
                            <option value="68" >Waikabubak</option>
                            <option value="69" >Tambolaka</option>
                            <option value="70" >Sukawinatan</option>
                            <option value="74" >Cilacap</option>
                            <option value="75" >Dumai</option>
                            <option value="77" >Ketapang</option>
                            <option value="78" >Tarakan</option>
                            <option value="79" >Pacitan</option>
                            <option value="80" >Rembang</option>
                            <option value="81" >Pedan</option>
                            <option value="82" >Klaten</option>
                            <option value="83" >Adipala</option>
                            <option value="85" >Kediri</option>
                            <option value="87" >Kutai</option>
                            <option value="89" >Tegal</option>
                            <option value="90" >Brebes</option>
                            <option value="91" >Purwokerto</option>
                            <option value="92" >Bangli</option>
                            <option value="93" >Buleleng</option>
                            <option value="94" >Gianyar</option>
                            <option value="95" >Karangasem</option>
                            <option value="96" >Badung</option>
                            <option value="97" >Tabanan</option>
                            <option value="98" >Klungkung</option>
                            <option value="99" >Jembrana</option>
                            <option value="102" >Pemalang</option>
                            <option value="103" >Purbalingga</option>
                            <option value="104" >Batang</option>
                            <option value="105" >Banyumas</option>
                            <option value="106" >Banjarnegara</option>
                            <option value="107" >Kebumen</option>
                            <option value="108" >Wonogiri</option>
                            <option value="109" >Sragen</option>
                            <option value="110" >Sukoharjo</option>
                            <option value="111" >Boyolali</option>
                            <option value="112" >Demak</option>
                            <option value="113" >Purworejo</option>
                            <option value="114" >Magelang</option>
                            <option value="121" >Palopo</option>
                            <option value="122" >Singapura</option>
                            <option value="125" >Samarinda</option>
                            <option value="126" >Pomalaa</option>
                            <option value="127" >Beijing</option>
                            <option value="128" >Meulaboh</option>
                            <option value="129" >New Delhi</option>
                            <option value="130" >Karnataka</option>
                            <option value="131" >Singkep</option>
                            <option value="132" >Lingga</option>
                            <option value="133" >Saumlaki</option>
                            <option value="134" >Sabang</option>
                            <option value="136" >Kendawangan</option>
                            <option value="137" >Jailolo</option>
                            <option value="138" >Halmahera Barat</option>
                            <option value="140" >Tanah Laut</option>
                            <option value="143" >Topang</option>
                            <option value="144" >Meranti</option>
                            <option value="145" >Selat Sugi</option>
                            <option value="146" >Aru Selatan</option>
                            <option value="147" >Wokam Aru Utara</option>
                            <option value="148" >Kaimana</option>
                            <option value="149" >Fak-fak</option>
                            <option value="150" >Toya Pakeh</option>
                            <option value="151" >Nusa Penida</option>
                            <option value="152" >Delta Mahakam</option>
                            <option value="153" >Simeulue</option>
                            <option value="154" >Aceh Singkil</option>
                            <option value="155" >Aceh Selatan</option>
                            <option value="156" >Aceh Tenggara</option>
                            <option value="157" >Aceh Timur</option>
                            <option value="158" >Aceh Tengah</option>
                            <option value="159" >Aceh Barat</option>
                            <option value="160" >Aceh Besar</option>
                            <option value="161" >Pidie</option>
                            <option value="162" >Bireuen</option>
                            <option value="163" >Aceh Utara</option>
                            <option value="164" >Aceh Barat Daya</option>
                            <option value="165" >Gayo Lues</option>
                            <option value="166" >Aceh Tamiang</option>
                            <option value="167" >Nagan Raya</option>
                            <option value="168" >Aceh Jaya</option>
                            <option value="169" >Bener Meriah</option>
                            <option value="170" >Pidie Jaya</option>
                            <option value="171" >Langsa</option>
                            <option value="172" >Lhokseumawe</option>
                            <option value="173" >Subulussalam</option>
                            <option value="174" >Nias</option>
                            <option value="175" >Mandailing Natal</option>
                            <option value="176" >Tapanuli Selatan</option>
                            <option value="177" >Tapanuli Tengah</option>
                            <option value="178" >Tapanuli Utara</option>
                            <option value="180" >Labuhan Batu</option>
                            <option value="181" >Asahan</option>
                            <option value="50" >Jakarta</option>
                            <option value="39" >Tangerang Selatan</option>
                            <option value="60" >Tangerang</option>
                            <option value="141" >Tasikmalaya</option>
                            <option value="46" >Sukabumi</option>
                            <option value="76" >Garut</option>
                            <option value="116" >Ciamis</option>
                            <option value="72" >Cianjur</option>
                            <option value="88" >Banten</option>
                            <option value="100" >Pandeglang</option>
                            <option value="5" >Bandar Lampung</option>
                            <option value="9" >Bengkulu</option>
                            <option value="120" >Sumedang</option>
                            <option value="119" >Karawang</option>
                            <option value="31" >Pangkal Pinang</option>
                            <option value="118" >Kuningan</option>
                            <option value="115" >Majalengka</option>
                            <option value="124" >Cisarua</option>
                            <option value="66" >Indramayu</option>
                            <option value="182" >Simalungun</option>
                            <option value="183" >Dairi</option>
                            <option value="184" >Karo</option>
                            <option value="185" >Deli Serdang</option>
                            <option value="186" >Langkat</option>
                            <option value="187" >Nias Selatan</option>
                            <option value="188" >Humbang Hasundutan</option>
                            <option value="189" >Pakpak barat</option>
                            <option value="190" >Samosir</option>
                            <option value="191" >Serdang Bedagai</option>
                            <option value="192" >Batu Bara</option>
                            <option value="52" >Cibinong</option>
                            <option value="101" >Lebak</option>
                            <option value="193" >Padang Lawas Utara</option>
                            <option value="194" >Padang Lawas</option>
                            <option value="195" >Labuhan Batu Selatan</option>
                            <option value="196" >Labuhan Batu Utara</option>
                            <option value="197" >Nias Utara</option>
                            <option value="198" >Nias Barat</option>
                            <option value="199" >Sibolga</option>
                            <option value="200" >Tanjung Barat</option>
                            <option value="201" >Pematang Siantar</option>
                            <option value="202" >Tebing Tinggi</option>
                            <option value="203" >Binjai</option>
                            <option value="204" >Padangsidimpuan</option>
                            <option value="205" >Gunungsitoli</option>
                            <option value="206" >Kepulauan Mentawai</option>
                            <option value="207" >Pesisir selatan</option>
                            <option value="208" >Sijunjung</option>
                            <option value="209" >Tanah Datar</option>
                            <option value="210" >Padang Pariaman</option>
                            <option value="211" >Agam</option>
                            <option value="212" >Lima Puluh Kota</option>
                            <option value="213" >Pasaman</option>
                            <option value="214" >Solok Selatan</option>
                            <option value="215" >Dharmasraya</option>
                            <option value="216" >Pasaman Barat</option>
                            <option value="217" >Solok</option>
                            <option value="218" >Sawah Lunto</option>
                            <option value="219" >Padang Panjang</option>
                            <option value="220" >Bukittinggi</option>
                            <option value="221" >Payakumbuh</option>
                            <option value="222" >Pariaman</option>
                            <option value="223" >Kuantan singingi</option>
                            <option value="224" >Indragiri Hulu</option>
                            <option value="225" >Indragiri Hilir</option>
                            <option value="226" >Pelalawan</option>
                            <option value="227" >Siak</option>
                            <option value="228" >Kampar</option>
                            <option value="229" >Bengkalis</option>
                            <option value="230" >Rokan Hilir</option>
                            <option value="231" >Kepulauan Meranti</option>
                            <option value="232" >Kerinci</option>
                            <option value="233" >Merangin</option>
                            <option value="234" >Sarolangun</option>
                            <option value="235" >Batang Hari</option>
                            <option value="236" >Muaro Jambi</option>
                            <option value="237" >Tanjung Jabung TImur</option>
                            <option value="238" >Tanjung Jabung Barat</option>
                            <option value="239" >Tebo</option>
                            <option value="240" >Bungo</option>
                            <option value="241" >Sungai Penuh</option>
                            <option value="242" >Ogan Komering Ulu</option>
                            <option value="243" >Ogan Komering Ilir</option>
                            <option value="244" >Muara Enim</option>
                            <option value="245" >Bolaang Mongondow Utara</option>
                            <option value="246" >Siau Tagulandang Biaro</option>
                            <option value="247" >Minahasa Tenggara</option>
                            <option value="248" >Bolaang Mongondow Selatan</option>
                            <option value="249" >Bolaang Mongondow Timur</option>
                            <option value="250" >Bitung</option>
                            <option value="251" >Tomohon</option>
                            <option value="252" >Kotamobagu</option>
                            <option value="253" >Banggai Kepulauan</option>
                            <option value="254" >Banggai</option>
                            <option value="255" >Morowali</option>
                            <option value="256" >Donggala</option>
                            <option value="257" >Buol</option>
                            <option value="258" >Parigi Moutong</option>
                            <option value="259" >Tojo Una-Una</option>
                            <option value="260" >Sigi</option>
                            <option value="261" >Selayar</option>
                            <option value="262" >Bulukumba</option>
                            <option value="263" >Bantaeng</option>
                            <option value="264" >Jeneponto</option>
                            <option value="265" >Takalar</option>
                            <option value="266" >Gowa</option>
                            <option value="267" >Sinjai</option>
                            <option value="268" >Maros</option>
                            <option value="269" >Pangkajene Dan Kepulauan</option>
                            <option value="270" >Barru</option>
                            <option value="271" >Bone</option>
                            <option value="272" >Soppeng</option>
                            <option value="273" >Wajo</option>
                            <option value="274" >Sidenreng Rappang</option>
                            <option value="275" >Pinrang</option>
                            <option value="276" >Enrekang</option>
                            <option value="277" >Luwu</option>
                            <option value="278" >Tana Toraja</option>
                            <option value="279" >Luwu Utara</option>
                            <option value="280" >Luwu Timur</option>
                            <option value="281" >Toraja Utara</option>
                            <option value="282" >Pare-Pare</option>
                            <option value="283" >Buton</option>
                            <option value="284" >Muna</option>
                            <option value="285" >Konawe</option>
                            <option value="286" >Kolaka</option>
                            <option value="287" >Konawe Selatan</option>
                            <option value="288" >Bombana</option>
                            <option value="289" >Lahat</option>
                            <option value="290" >Musi Rawas</option>
                            <option value="291" >Musi Banyuasin</option>
                            <option value="292" >Banyuasin</option>
                            <option value="293" >Empat Lawang</option>
                            <option value="294" >Prabumulih</option>
                            <option value="295" >Pagar Alam</option>
                            <option value="296" >Lubuklinggau</option>
                            <option value="324" >Karimun</option>
                            <option value="325" >Bintan</option>
                            <option value="326" >Natuna</option>
                            <option value="327" >Kepulauan Anambas</option>
                            <option value="328" >Kepulauan Seribu</option>
                            <option value="329" >Jakarta Selatan</option>
                            <option value="330" >Jakarta Timur</option>
                            <option value="331" >Jakarta Pusat</option>
                            <option value="332" >Jakarta Barat</option>
                            <option value="333" >Jakarta Utara</option>
                            <option value="337" >Wonosobo</option>
                            <option value="338" >Karanganyar</option>
                            <option value="339" >Grobogan</option>
                            <option value="340" >Pati</option>
                            <option value="341" >Kudus</option>
                            <option value="342" >Jepara</option>
                            <option value="343" >Temanggung</option>
                            <option value="344" >Kendal</option>
                            <option value="345" >Salatiga</option>
                            <option value="346" >Kulon Progo</option>
                            <option value="347" >Bantul</option>
                            <option value="348" >Gunung Kidul</option>
                            <option value="349" >Sleman</option>
                            <option value="350" >Ponorogo</option>
                            <option value="351" >Trenggalek</option>
                            <option value="352" >Tulungagung</option>
                            <option value="334" >Bandung Barat</option>
                            <option value="319" >Bangka</option>
                            <option value="335" >Cimahi</option>
                            <option value="323" >Belitung Timur</option>
                            <option value="353" >Blitar</option>
                            <option value="354" >Lumajang</option>
                            <option value="355" >Jember</option>
                            <option value="356" >Banyuwangi</option>
                            <option value="357" >Bondowoso</option>
                            <option value="358" >Situbondo</option>
                            <option value="359" >Probolinggo</option>
                            <option value="360" >Pasuruan</option>
                            <option value="361" >Sidoarjo</option>
                            <option value="362" >Mojokerto</option>
                            <option value="363" >Jombang</option>
                            <option value="364" >Nganjuk</option>
                            <option value="365" >Madiun</option>
                            <option value="303" >Bengkulu Tengah</option>
                            <option value="304" >Bengkulu Utara</option>
                            <option value="298" >Kaur</option>
                            <option value="302" >Kepahiang</option>
                            <option value="301" >Lebong</option>
                            <option value="300" >Mukomuko</option>
                            <option value="322" >Bangka Selatan</option>
                            <option value="315" >Kabupaten Pringsewu</option>
                            <option value="299" >Seluma</option>
                            <option value="313" >Kabupaten Tulang Bawang</option>
                            <option value="316" >Kabupaten Mesuji</option>
                            <option value="318" >Metro</option>
                            <option value="320" >Bangka Barat</option>
                            <option value="311" >Kabupaten Lampung Utara</option>
                            <option value="307" >Kabupaten Tanggamus</option>
                            <option value="321" >Bangka Tengah</option>
                            <option value="308" >Kabupaten Lampung Selatan</option>
                            <option value="310" >Kabupaten Lampung Tengah</option>
                            <option value="309" >Kabupaten Lampung Timur</option>
                            <option value="312" >Kabupaten Way Kanan</option>
                            <option value="366" >Magetan</option>
                            <option value="367" >Ngawi</option>
                            <option value="368" >Bojonegoro</option>
                            <option value="369" >Tuban</option>
                            <option value="370" >Lamongan</option>
                            <option value="371" >Gresik</option>
                            <option value="372" >Bangkalan</option>
                            <option value="373" >Sampang</option>
                            <option value="374" >Pamekasan</option>
                            <option value="375" >Sumenep</option>
                            <option value="376" >Batu</option>
                            <option value="377" >Karang Asem</option>
                            <option value="378" >Lombok Barat</option>
                            <option value="379" >Lombok Tengah</option>
                            <option value="380" >Lombok Timur</option>
                            <option value="381" >Sumbawa</option>
                            <option value="382" >Dompu</option>
                            <option value="383" >Bima</option>
                            <option value="384" >Sumbawa Barat</option>
                            <option value="385" >Lombok Utara</option>
                            <option value="386" >Sumba Barat</option>
                            <option value="387" >Sumba Timur</option>
                            <option value="388" >Timor Tengah Selatan</option>
                            <option value="389" >Timor Tengah Utara</option>
                            <option value="390" >Belu</option>
                            <option value="391" >Alor</option>
                            <option value="392" >Lembata</option>
                            <option value="393" >Flores Timur</option>
                            <option value="394" >Sikka</option>
                            <option value="395" >Ende</option>
                            <option value="396" >Ngada</option>
                            <option value="397" >Manggarai</option>
                            <option value="398" >Rote Ndao</option>
                            <option value="399" >Manggarai Barat</option>
                            <option value="400" >Sumba Tengah</option>
                            <option value="401" >Sumba Barat Daya</option>
                            <option value="402" >Nagekeo</option>
                            <option value="403" >Manggarai Timur</option>
                            <option value="404" >Sabu Raijua</option>
                            <option value="405" >Sambas</option>
                            <option value="406" >Bengkayang</option>
                            <option value="407" >Landak</option>
                            <option value="408" >Sanggau</option>
                            <option value="409" >Sintang</option>
                            <option value="410" >Kapuas Hulu</option>
                            <option value="411" >Sekadau</option>
                            <option value="412" >Melawi</option>
                            <option value="413" >Kayong Utara</option>
                            <option value="414" >Wakatobi</option>
                            <option value="415" >Kolaka Utara</option>
                            <option value="416" >Buton Utara</option>
                            <option value="417" >Konawe Utara</option>
                            <option value="418" >Bau-Bau</option>
                            <option value="419" >Boalemo</option>
                            <option value="420" >Pohuwato</option>
                            <option value="421" >Bone Bolango</option>
                            <option value="422" >Gorontalo Utara</option>
                            <option value="423" >Majene</option>
                            <option value="424" >Polewali Mandar</option>
                            <option value="425" >Mamasa</option>
                            <option value="426" >Mamuju Utara</option>
                            <option value="427" >Maluku Tenggara Barat</option>
                            <option value="428" >Maluku Tenggara</option>
                            <option value="429" >Maluku Tengah</option>
                            <option value="430" >Buru</option>
                            <option value="431" >Kepulauan Aru</option>
                            <option value="432" >Seram Bagian Barat</option>
                            <option value="433" >Seram Bagian Timur</option>
                            <option value="434" >Maluku Barat Daya</option>
                            <option value="435" >Buru Selatan</option>
                            <option value="436" >Tual</option>
                            <option value="437" >Halmahera Tengah</option>
                            <option value="438" >Kepulauan Sula</option>
                            <option value="439" >Halmahera Selatan</option>
                            <option value="440" >Halmahera Utara</option>
                            <option value="441" >Halmahera Timur</option>
                            <option value="442" >Pulau Morotai</option>
                            <option value="443" >Tidore Kepulauan</option>
                            <option value="444" >Fakfak</option>
                            <option value="445" >Teluk Wondama</option>
                            <option value="446" >Teluk Bintuni</option>
                            <option value="447" >Sorong Selatan</option>
                            <option value="448" >Raja Ampat</option>
                            <option value="449" >Tambrauw</option>
                            <option value="450" >Maybrat</option>
                            <option value="451" >Merauke</option>
                            <option value="452" >Jayawijaya</option>
                            <option value="453" >Nabire</option>
                            <option value="454" >Kepulauan Yapen</option>
                            <option value="455" >Biak Numfor</option>
                            <option value="456" >Paniai</option>
                            <option value="457" >Puncak Jaya</option>
                            <option value="458" >Mimika</option>
                            <option value="459" >Boven Digoel</option>
                            <option value="460" >Mappi</option>
                            <option value="461" >Asmat</option>
                            <option value="462" >Yahukimo</option>
                            <option value="463" >Pegunungan Bintang</option>
                            <option value="464" >Tolikara</option>
                            <option value="465" >Sarmi</option>
                            <option value="467" >Waropen</option>
                            <option value="468" >Kubu Raya</option>
                            <option value="469" >Singkawang</option>
                            <option value="470" >Kotawaringin Barat</option>
                            <option value="471" >Kotawaringin Timur</option>
                            <option value="472" >Kapuas</option>
                            <option value="473" >Barito Selatan</option>
                            <option value="474" >Barito Utara</option>
                            <option value="475" >Sukamara</option>
                            <option value="476" >Lamandau</option>
                            <option value="477" >Seruyan</option>
                            <option value="478" >Katingan</option>
                            <option value="479" >Pulau Pisau</option>
                            <option value="480" >Gunung mas</option>
                            <option value="481" >Barito Timur</option>
                            <option value="482" >Murung Raya</option>
                            <option value="483" >Kota Baru</option>
                            <option value="484" >Banjar Kalimantan Selatan</option>
                            <option value="485" >Barito Kuala</option>
                            <option value="486" >Tapin</option>
                            <option value="487" >Hulu Sungai Selatan</option>
                            <option value="488" >Hulu Sungai Tengah</option>
                            <option value="489" >Hulu sungai Utara</option>
                            <option value="490" >Tabalong</option>
                            <option value="491" >Tanah Bumbu</option>
                            <option value="492" >Balangan</option>
                            <option value="493" >Banjar Baru</option>
                            <option value="494" >Paser</option>
                            <option value="495" >Kutai Barat</option>
                            <option value="496" >Kutai Kartanegara</option>
                            <option value="497" >Kutai timur</option>
                            <option value="498" >Berau</option>
                            <option value="499" >Malinau</option>
                            <option value="500" >Bulungan</option>
                            <option value="501" >Nunukan</option>
                            <option value="502" >Penajam Paser Utara</option>
                            <option value="503" >Tana Tidung</option>
                            <option value="504" >Bontang</option>
                            <option value="505" >Kepulauan Sangihe</option>
                            <option value="506" >Kepulauan Talaud</option>
                            <option value="507" >Minahasa</option>
                            <option value="508" >Minahasa Selatan</option>
                            <option value="509" >Minahasa Utara</option>
                            <option value="510" >Sampit</option>
                            <option value="511" >New York</option>
                            <option value="512" >Luwuk</option>
                            <option value="516" >Papua Nugini</option>
                            <option value="517" >Wina</option>
                            <option value="518" >Paiton</option>
                            <option value="519" >Teheran</option>
                            <option value="57" >Luang Prabang</option>
                            <option value="520" >Berlin</option>
                            <option value="521" >Bonn</option>
                            <option value="522" >Dubai</option>
                            <option value="523" >Azerbaijan</option>
                            <option value="525" >Bandung</option>
                            <option value="526" >Subang</option>
                            <option value="527" >Depok</option>
                            <option value="513" >Cikampek</option>
                            <option value="528" >Surabaya</option>
                            <option value="529" >Pangandaran</option>
                            <option value="336" >Banjar Jawa Barat</option>
                            <option value="530" >Cilegon</option>
                            <option value="531" >Belitung</option>
                            <option value="532" >Kabupaten Bandung</option>
                            <option value="533" >Balikpapan</option>
                            <option value="534" >Mempawah</option>
                            <option value="535" >Wayame</option>
                            <option value="536" >Baubau</option>
                            <option value="537" >Ambon</option>
                            <option value="538" >Tanjung Selor</option>
                            <option value="539" >Taliabu</option>
                            <option value="540" >Sidrap</option>
                            <option value="541" >Sofifi</option>
                            <option value="542" >Semeru</option>
                            <option value="73" >Cikarang</option>
                            <option value="305" >Bengkulu Selatan</option>
                            <option value="297" >Rejang Lebong</option>
                            <option value="543" >Kabupaten Tangerang</option>
                            <option value="544" >Jenewa</option>
                            <option value="545" >Kabupaten Bekasi</option>
                            <option value="546" >Kabupaten Bogor</option>
                            <option value="547" >Pangkep</option>
                            <option value="548" >Deiyai</option>
                            <option value="549" >Mamuju Tengah</option>
                            <option value="550" >Teheran</option>
                            <option value="551" >Doha</option>
                            <option value="552" >Cape Town</option>
                            <option value="553" >Davos</option>
                            <option value="555" >Barcelona</option>
                            <option value="556" >Kigali</option>
                            <option value="557" >Ulan Bator</option>
                            <option value="558" >Amsterdam</option>
                            <option value="559" >Copenhagen</option>
                            <option value="560" >Oslo</option>
                            <option value="561" >Reykjavik</option>
                            <option value="562" >Stockholm</option>
                            <option value="563" >Brussel</option>
                            <option value="564" >Labuan Bajo</option>
                            <option value="565" >Babo</option>
                            <option value="566" >Pasangkayu</option>
                            <option value="567" >Penukal Abab Lematang Ilir</option>
                            <option value="568" >Pegunungan Arfak</option>
                            <option value="569" >Lanny Jaya</option>
                            <option value="570" >Sydney</option>
                            <option value="571" >Nevada</option>
                            <option value="572" >Kongens Lyngby</option>
                            <option value="573" >Milan</option>
                            <option value="574" >Ottawa</option>
                            <option value="575" >Vancouver</option>
                            <option value="576" >Edmonton</option>
                            <option value="577" >Kuala Lumpur</option>
                            <option value="578" >Brisbane</option>
                            <option value="579" >Melbourne</option>
                            <option value="580" >Pittsburgh</option>
                            <option value="581" >Ho Chi Minh</option>
                            <option value="582" >Vienna</option>
                            <option value="583" >Bangkok</option>
                            <option value="584" >Sapporo</option>
                            <option value="585" >Aberdeen</option>
                            <option value="586" >Sussex</option>
                            <option value="587" >Ogan Ilir</option>
                            <option value="588" >Kabupaten Probolinggo</option>
                            <option value="589" >Kabupaten Pasuruan</option>
                            <option value="590" >Manila</option>
                            <option value="591" >Seoul</option>
                            <option value="592" >Rokan Hulu</option>
                            <option value="593" >Helsinki</option>
                            <option value="594" >Sharm el-Sheikh</option>
                            <option value="596" >Busan</option>
                            <option value="597" >Kairo</option>
                            <option value="598" >Kabupaten Semarang</option>
                            <option value="599" >Kabupaten Magelang</option>
                            <option value="600" >Kabupaten Tegal</option>
                            <option value="601" >Roma</option>
                            <option value="602" >Batulicin</option>
                            <option value="603" >Canberra</option>
                            <option value="604" >Kepulauan Tanimbar</option>
                            <option value="605" >Lawe-Lawe</option>
                            <option value="606" >Balongan</option>
                            <option value="607" >Daejeon</option>

                            <option value="608" >Perth</option>
                            <option value="179" >Toba</option>
                            <option value="609" >Riyadh</option>
                            <option value="306" >Kabupaten Lampung Barat</option>
                            <option value="314" >Kabupaten Pesawaran</option>
                            <option value="610" >Kabupaten Pesisir Barat</option>
                            <option value="317" >Kabupaten Tulang Bawang Barat</option>
                            <option value="611" >Bengaluru</option>
                            <option value="612" >Budapest</option>
                            <option value="514" >Washington</option>
                            <option value="613" >Houston</option>
                            <option value="614" >Kabupaten Cirebon</option>
                            <option value="615" >California</option>
                            <option value="616" >Kabupaten Bolaang Mongondow</option>
                            <option value="617" >Gandhinagar</option>
                            <option value="618" >Merak</option>
                            <option value="619" >Cilegon</option>
                            <option value="620" >Vientiane</option>
                            <option value="621" >Nanning</option>
                            <option value="622" >Mumbai</option>
                            <option value="623" >Detroit</option>
                            <option value="624" >Pnom Penh</option>
                            <option value="625" >Moskow</option>
                            <option value="626" >Rotterdam</option>
                            <option value="627" >Gibraltar</option>
                            <option value="628" >Dakar</option>
                            <option value="466" >Kabupaten Keerom</option>
                            <option value="629" >Kyoto</option>
                            <option value="630" >Hanoi</option>
                            <option value="631" >Da Nang</option>
                            <option value="632" >Goa</option>
                            <option value="633" >Nanjing</option>
                            <option value="634" >Fuzhou</option>
                            <option value="635" >Shanghai</option>
                            <option value="636" >Bergen</option>
                            <option value="637" >Manokwari Selatan</option>
                            <option value="638" >Bern</option>
                            <option value="639" >Miami</option>
                            <option value="640" >Chicago</option>
                            <option value="641" >Seattle</option>
                            <option value="642" >Illinois</option>
                            <option value="643" >Andowia</option>
                            <option value="644" >Lamonae</option>
                            <option value="645" >Nairobi</option>
                            <option value="646" >Dar es Salaam</option>
                            <option value="647" >Madrid</option>
                            <option value="648" >Supiori</option>
                            <option value="649" >Kabupaten Malaka</option>
                            <option value="650" >Marquette</option>
                            <option value="651" >Sudbury</option>
                            <option value="653" >Haikou</option>
                            <option value="652" >Wuxi City</option>
                            <option value="654" >Calgary</option>
                            <option value="655" >Hainan</option>
                            <option value="656" >Guangzhou</option>
                            <option value="657" >Kushiro</option>
                            <option value="658" >Palawan</option>
                            <option value="659" >Tanjung Balai</option>
                            <option value="661" >Astana</option>
                            <option value="662" >Hokkaido</option>
                            <option value="663" >Shenzhen</option>
                            <option value="664" >Auckland</option>
                            <option value="665" >Phang Nga Bay</option>
                            <option value="666" >Bandar Seri Begawan</option>
                            <option value="667" >San Fransisco</option>
                            <option value="668" >Johor Bahru</option>
                            <option value="669" >Santiago</option>
                            <option value="670" >Mandalika</option>
                            <option value="671" >Kabupaten Karawang</option>
                        </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                        <label for="tgl_berangkat">Tanggal Berangkat *</label>
                        <input type="date" class="form-control" id="tgl_berangkat" name="tgl_berangkat" placeholder="Tanggal Berangkat">
                        </div>
                        <div class="form-group col-md-6">
                        <label for="tgl_pulang">Tanggal Pulang</label>
                        <input type="date" class="form-control" id="tgl_pulang" name="tgl_pulang" placeholder="Tanggal Pulang">
                        </div>
                    </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="pagu_awal">Tiket</label>
                      <input type="number" required name="pagu_awal" min="0" class="form-control" id="pagu_awal" placeholder="Tiket">
                    </div>
                    <div class="form-group col-md-6">
                      <label for="tahun_anggaran">Transportasi</label>
                      <input type="number" min="1000" required class="form-control" name="tahun_anggaran" id="tahun_anggaran" placeholder="Transportasi">
                      {{-- <div class="invalid-feedback">
                        Please provide a valid city.
                      </div> --}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="akun">Uang Harian</label>
                    <input type="number" required name="akun" min="0" class="form-control" id="akun" placeholder="Uang Harian">
                </div>
                <div class="form-group">
                    <label for="akun">Biaya Penginapan</label>
                    <input type="number" required name="akun" min="0" class="form-control" id="akun" placeholder="Uang Harian">
                </div>
                  
                  <a href="{{ route('spd.pelaksana.index',1) }}" class="btn btn-secondary">Kembali</a>
                  <button type="submit" class="btn btn-warning">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End XP Contentbar -->
@endsection 
@section('script')
<!-- Select2 JS -->
<script src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>
<script src="{{ asset('assets/js/init/form-select-init.js') }}"></script>
<!-- Tagsinput JS -->
<script src="{{ asset('assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-tagsinput/typeahead.bundle.js') }}"></script>
<script src="{{ asset('assets/js/init/form-select-init.js') }}"></script>
@endsection 